//! WSPR differential against an independent implementation.
//!
//! # Why this exists
//!
//! Until this file, WSPR was validated **entirely by self-consistency**:
//! a closed transmit-to-receive loop plus component known-answer tests,
//! with no external audio, no reference binary and no published
//! end-to-end vector. `tests/wspr.rs` says so in its own provenance
//! note — its frozen 162-symbol snapshot is generated by this
//! implementation, so it detects regressions, not spec errors.
//!
//! That is precisely the shape of the IL2P defect (see
//! `docs/APRS_CONFORMANCE.md` §6.1): an encoder and a decoder that are
//! mutual inverses stay mutual inverses when a shared constant is
//! wrong, so every round-trip test passed while the mode could not
//! exchange a single frame with anybody. WSPR had the same exposure and
//! no way to detect it.
//!
//! These three tests close it, in increasing order of scope:
//!
//! 1. **Channel symbols** — our 162 symbols against the reference
//!    encoder's, for several messages. This is the strongest and
//!    cheapest check: it compares the entire source encoding,
//!    convolutional code, interleave and sync merge as one composed
//!    value, which is exactly the layer a wrong constant hides in.
//! 2. **Our transmission, their decoder** — real audio out of our
//!    modulator, decoded by the reference decoder.
//! 3. **Their transmission, our decoder** — real audio out of the
//!    reference generator, decoded by our receive engine.
//!
//! # Running
//!
//! Needs three binaries from an independent WSPR implementation, located
//! through environment variables so that no tracked file hardcodes a
//! path into `reference/` (see CONTRIBUTING.md):
//!
//! ```text
//! WARBLE_REF_WSPR_ENCODE=/path/to/symbol-printing encoder
//! WARBLE_REF_WSPR_GEN=/path/to/wav-writing generator
//! WARBLE_REF_WSPR_DECODE=/path/to/decoder
//!   cargo test --release --all-features --test wspr_differential -- --ignored --nocapture
//! ```
//!
//! Each test skips with a message when its binary is absent, so a
//! contributor without them still gets a fully green `cargo test`.
#![cfg(all(feature = "wspr", feature = "std"))]

use std::path::{Path, PathBuf};
use std::process::Command;

use warble::SampleRate;
use warble::geo::MaidenheadGrid;
use warble::wspr::{
    SYMBOL_COUNT, WsprConfig, WsprDecoder, WsprDecoderConfig, WsprMessage, WsprModulator,
};

/// The canonical WSPR working rate; the protocol is defined at it.
const RATE_HZ: u32 = 12_000;
/// A WSPR slot is two minutes; the transmission occupies ~110.6 s of it.
const SLOT_SAMPLES: usize = 120 * RATE_HZ as usize;
/// Transmissions nominally start one second into the slot.
const LEAD_IN_SAMPLES: usize = RATE_HZ as usize;
/// Centre of the WSPR sub-band, and of both implementations' search.
const CENTER_HZ: u32 = 1_500;

/// The messages exercised in both directions.
///
/// Chosen to move every field of the source encoding: the callsign
/// alignment rule (a two-character prefix versus one, and a short call
/// needing trailing padding), both extremes of the locator range, and
/// the extremes of the power field.
///
/// Note the crate's usual placeholder `N0CALL` is absent, and cannot be
/// used here: WSPR type 1 requires the third character to be a digit
/// after alignment, and a six-character callsign with its digit in
/// second position cannot be shifted right without overflowing the
/// six-character field. Real stations in that shape use the hashed
/// two-transmission format, which this crate does not implement.
const CASES: &[(&str, &str, u8)] = &[
    ("K1ABC", "FN42", 37),
    ("G4JNT", "IO90", 30),
    ("KA1ABC", "AA00", 0),
    ("VE3XYZ", "RR99", 60),
    ("W1AW", "FN31", 23),
];

/// The least breadth each leg claims.
///
/// Every assertion in this file lives inside a loop over [`CASES`], so
/// an empty list would make all three tests pass having compared
/// nothing — the one failure mode a suite cannot report on itself.
/// Stating the count also documents what "5/5" is out of.
const MIN_CASES: usize = 5;

/// Looks up a reference binary, or `None` to skip.
fn ref_binary(var: &str) -> Option<PathBuf> {
    let path = PathBuf::from(std::env::var_os(var)?);
    // Unset means "this contributor does not have the binaries", which
    // is a legitimate skip. Set-but-wrong means somebody typed a path
    // and meant to run this, so it is a hard failure -- otherwise a
    // single typo turns an entire interoperability suite green while it
    // tests nothing at all, which is the most expensive way a test can
    // fail. `tests/differential.rs` has always asserted this; these
    // suites had drifted from it.
    assert!(
        path.is_file(),
        "{var}={} does not point to an existing file. Unset the variable \
         to skip this suite deliberately; leaving it set and wrong would \
         pass without testing anything.",
        path.display()
    );
    // Absolute, because the tests below run these binaries with a working
    // directory of their own (see `scratch_subdir`). Rust documents a
    // relative program path combined with `current_dir` as platform
    // specific, and where it does not work the failure reads as a missing
    // binary -- indistinguishable from the typo case this function exists
    // to report.
    Some(
        path.canonicalize()
            .unwrap_or_else(|e| panic!("{var}={}: {e}", path.display())),
    )
}

/// A private, empty scratch directory for one test's generated audio.
///
/// Each test gets its own subdirectory rather than sharing `scratch/`,
/// because the reference binaries write working files of their own
/// there (a decoded-spot log and a callsign hash table). Those landing
/// beside the benchmark fixtures is how a stale file quietly starts
/// influencing a later run.
fn scratch_subdir(name: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("scratch")
        .join(name);
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

fn message(callsign: &str, locator: &str, power: u8) -> WsprMessage {
    WsprMessage::new(
        callsign,
        MaidenheadGrid::new(locator).expect("valid locator"),
        power,
    )
    .expect("valid message")
}

/// Our modulator's output, padded into a full two-minute slot.
///
/// The reference decoder expects a whole slot with the transmission one
/// second in; ours is indifferent to the padding, so this is the shape
/// both accept.
fn our_slot_samples(msg: &WsprMessage) -> Vec<i16> {
    let config =
        WsprConfig::new(CENTER_HZ, SampleRate::new(RATE_HZ).expect("valid rate")).expect("config");
    let mut samples = vec![0i16; LEAD_IN_SAMPLES];
    samples.extend(WsprModulator::for_message(config, msg));
    samples.resize(SLOT_SAMPLES, 0);
    samples
}

fn write_wav(path: &PathBuf, samples: &[i16]) {
    let spec = hound::WavSpec {
        channels: 1,
        sample_rate: RATE_HZ,
        bits_per_sample: 16,
        sample_format: hound::SampleFormat::Int,
    };
    let mut writer = hound::WavWriter::create(path, spec).expect("create wav");
    for &s in samples {
        writer.write_sample(s).expect("write sample");
    }
    writer.finalize().expect("finalize wav");
}

fn read_wav(path: &PathBuf) -> Vec<i16> {
    let mut reader = hound::WavReader::open(path).expect("open wav");
    assert_eq!(reader.spec().sample_rate, RATE_HZ, "reference wav rate");
    assert_eq!(reader.spec().channels, 1, "reference wav channels");
    reader
        .samples::<i16>()
        .map(|s| s.expect("sample"))
        .collect()
}

/// The header a symbol-printing encoder puts above the channel symbols.
const SYMBOL_HEADER: &str = "Channel symbols:";

/// Argument forms tried, in this fixed order, when asking the encoder
/// for one message's symbols.
///
/// Two shapes of symbol-printing encoder exist and the variable does not
/// say which one it names: a dedicated encoder dissects the message it is
/// given and takes nothing else, while a simulator prints its symbols
/// only when asked for them with a flag. Trying both is what makes
/// `WARBLE_REF_WSPR_ENCODE` mean "a symbol-printing WSPR encoder" rather
/// than "one specific build", and guessing wrong is not a theoretical
/// risk: it is why this test had never once run (see
/// [`reference_symbols`]).
///
/// The order is fixed and the search stops at the first form that
/// produces symbols, so a run is reproducible.
const ENCODER_ARG_FORMS: [&[&str]; 2] = [&["-c"], &[]];

/// Pulls [`SYMBOL_COUNT`] channel symbols out of one encoder report.
///
/// Tokens are read from after [`SYMBOL_HEADER`] until enough have been
/// collected, stopping at the first token that is not a number, because
/// the symbols may be printed on one long line **or wrapped across
/// several** and the report continues with prose either way. Splitting on
/// the header also keeps the data-symbol and sync-symbol sections some
/// encoders print first — same shape, different meaning — out of the
/// comparison.
fn parse_symbols(stdout: &str) -> Option<Vec<u8>> {
    let (_, after) = stdout.split_once(SYMBOL_HEADER)?;
    let symbols: Vec<u8> = after
        .split_whitespace()
        .map_while(|token| token.parse::<u8>().ok())
        .take(SYMBOL_COUNT)
        .collect();
    (symbols.len() == SYMBOL_COUNT).then_some(symbols)
}

/// Asks the reference encoder for one message's channel symbols.
///
/// This is the part of the suite that had never executed. Its first form
/// passed a flag and then searched for all [`SYMBOL_COUNT`] symbols on a
/// single line, which meant that against an encoder wrapping them it
/// could only ever panic, and against an encoder taking no flag it handed
/// over the flag itself **as the message**. Either way the leg that
/// compares this crate's composed WSPR encoding against an independent
/// one — the whole reason this file exists — reported nothing.
fn reference_symbols(encoder: &Path, text: &str) -> Vec<u8> {
    let mut transcript = String::new();
    for form in ENCODER_ARG_FORMS {
        let output = Command::new(encoder)
            .args(form)
            .arg(text)
            .output()
            .expect("run the reference encoder");
        let stdout = String::from_utf8_lossy(&output.stdout);
        if let Some(symbols) = parse_symbols(&stdout) {
            return symbols;
        }
        transcript.push_str(&format!("--- argument form {form:?} ---\n{stdout}"));
    }
    panic!(
        "the reference encoder printed no {SYMBOL_COUNT}-symbol \
         {SYMBOL_HEADER:?} section for {text:?} in any known argument \
         form. Point WARBLE_REF_WSPR_ENCODE at an encoder that prints \
         channel symbols.\n{transcript}"
    );
}

/// Renders a message the way both implementations spell it on a line.
fn rendered(msg: &WsprMessage) -> String {
    format!(
        "{} {} {}",
        String::from_utf8_lossy(msg.callsign()).trim(),
        msg.grid(),
        msg.power_dbm()
    )
}

// ---------------------------------------------------------------------
// 1. Channel symbols — the composed encoding, against an independent one
// ---------------------------------------------------------------------

/// Every one of the 162 channel symbols must match the reference
/// encoder's, for every message.
///
/// This is the test the crate most needed and did not have. A wrong
/// constant anywhere in the source packing, the convolutional
/// polynomials, the interleave permutation or the sync merge changes at
/// least one symbol here, and no amount of internal round-tripping can
/// see any of them.
#[test]
#[ignore = "requires WARBLE_REF_WSPR_ENCODE"]
fn channel_symbols_match_the_reference_encoder() {
    let Some(encoder) = ref_binary("WARBLE_REF_WSPR_ENCODE") else {
        eprintln!("WARBLE_REF_WSPR_ENCODE not set — skipping");
        return;
    };

    assert!(CASES.len() >= MIN_CASES, "case list shrank");
    let mut compared = 0usize;
    for &(callsign, locator, power) in CASES {
        let msg = message(callsign, locator, power);
        let text = rendered(&msg);

        let theirs = reference_symbols(&encoder, &text);

        let ours = msg.channel_symbols();
        assert_eq!(
            ours.as_slice(),
            theirs.as_slice(),
            "channel symbols differ for {text:?}\n ours: {ours:?}\ntheirs: {theirs:?}"
        );
        // Every symbol is a sync bit plus twice a data bit.
        assert!(ours.iter().all(|&s| s <= 3), "symbol out of range");
        compared += 1;
    }
    assert_eq!(compared, CASES.len());
    println!(
        "channel symbols: {compared}/{} messages identical",
        CASES.len()
    );
}

// ---------------------------------------------------------------------
// 2. Our transmission -> their decoder
// ---------------------------------------------------------------------

/// The reference decoder must recover our message from our audio.
#[test]
#[ignore = "requires WARBLE_REF_WSPR_DECODE"]
fn our_transmission_decodes_in_the_reference_decoder() {
    let Some(decoder) = ref_binary("WARBLE_REF_WSPR_DECODE") else {
        eprintln!("WARBLE_REF_WSPR_DECODE not set — skipping");
        return;
    };
    let dir = scratch_subdir("wspr_ref_decode");

    assert!(CASES.len() >= MIN_CASES, "case list shrank");
    let mut decoded = 0usize;
    for &(callsign, locator, power) in CASES {
        let msg = message(callsign, locator, power);
        // The reference derives a timestamp from the file name, so it
        // must look like one of its captures.
        let path = dir.join(format!("250101_{:04}.wav", 1000 + decoded));
        write_wav(&path, &our_slot_samples(&msg));

        let output = Command::new(&decoder)
            .current_dir(&dir)
            .arg("-f")
            .arg("14.0956")
            .arg(&path)
            .output()
            .expect("run the reference decoder");
        let stdout = String::from_utf8_lossy(&output.stdout);

        // The reference right-aligns the power in a two-column field,
        // so "... AA00  0" carries two spaces. Compare on
        // whitespace-normalised lines rather than raw substrings.
        let expected = rendered(&msg);
        let normalized: Vec<String> = stdout
            .lines()
            .map(|line| line.split_whitespace().collect::<Vec<_>>().join(" "))
            .collect();
        assert!(
            normalized.iter().any(|line| line.ends_with(&expected)),
            "the reference decoder did not recover {expected:?} from our audio:\n{stdout}"
        );
        let _ = std::fs::remove_file(&path);
        decoded += 1;
    }
    let _ = std::fs::remove_dir_all(&dir);
    println!(
        "our audio, their decoder: {decoded}/{} recovered",
        CASES.len()
    );
}

// ---------------------------------------------------------------------
// 3. Their transmission -> our decoder
// ---------------------------------------------------------------------

/// Our receive engine must recover the reference's message from the
/// reference's audio.
///
/// Note the frequency convention differs and that is not an error: the
/// reference places its `f0` at the **centre** of the four tones, while
/// this crate's `WsprConfig` names **tone 0**. The two differ by
/// `1.5 * 12000/8192` = 2.2 Hz, which the assertion below pins rather
/// than papers over — agreement to within a couple of hertz would have
/// hidden a real geometry error.
#[test]
#[ignore = "requires WARBLE_REF_WSPR_GEN"]
fn we_decode_the_reference_transmission() {
    let Some(generator) = ref_binary("WARBLE_REF_WSPR_GEN") else {
        eprintln!("WARBLE_REF_WSPR_GEN not set — skipping");
        return;
    };
    let dir = scratch_subdir("wspr_ref_gen");

    assert!(CASES.len() >= MIN_CASES, "case list shrank");
    let decoder = WsprDecoder::new(WsprDecoderConfig::new(CENTER_HZ, 100).expect("config"));
    let mut decoded = 0usize;
    for &(callsign, locator, power) in CASES {
        for entry in std::fs::read_dir(&dir).expect("read gen dir").flatten() {
            let _ = std::fs::remove_file(entry.path());
        }
        let msg = message(callsign, locator, power);
        let text = rendered(&msg);

        // args: message f0 DT fspread delay nwav nfiles snr
        // f0 = 0 is the sub-band centre; fspread/delay 0 keep the
        // channel clean; snr >= 90 disables the noise generator.
        let status = Command::new(&generator)
            .current_dir(&dir)
            .args([&text, "0", "0.0", "0.0", "0.0", "1", "1", "99"])
            .output()
            .expect("run the reference generator");
        assert!(
            status.status.success(),
            "reference generator failed: {}",
            String::from_utf8_lossy(&status.stderr)
        );

        let wav = std::fs::read_dir(&dir)
            .expect("read gen dir")
            .flatten()
            .map(|e| e.path())
            .find(|p| p.extension().is_some_and(|e| e == "wav"))
            .expect("the reference generator wrote no wav");

        let samples = read_wav(&wav);
        assert_eq!(samples.len(), SLOT_SAMPLES, "a full two-minute slot");

        let decodes = decoder.decode(&samples).expect("decode");
        let found = decodes
            .iter()
            .find(|d| rendered(&d.message) == text)
            .unwrap_or_else(|| {
                panic!(
                    "we did not recover {text:?} from the reference's audio; got {:?}",
                    decodes
                        .iter()
                        .map(|d| rendered(&d.message))
                        .collect::<Vec<_>>()
                )
            });

        // Tone 0 sits 1.5 tone spacings below the centre the reference
        // names. 12000/8192 Hz per tone.
        let expected_tone0 = f64::from(CENTER_HZ) - 1.5 * 12_000.0 / 8_192.0;
        assert!(
            (f64::from(found.freq_hz) - expected_tone0).abs() < 0.5,
            "tone 0 reported at {} Hz, expected {expected_tone0:.2} Hz",
            found.freq_hz
        );
        decoded += 1;
    }
    let _ = std::fs::remove_dir_all(&dir);
    println!(
        "their audio, our decoder: {decoded}/{} recovered",
        CASES.len()
    );
}
